### ISSUE TITLE
Failed to validate datapack NPE

### ISSUE THREAD

**Issue by jenzelc** [WerDei/Biome-Replacer#18]
Hello! Using Java 8, Fabric API 0.106.0+1.21.1, and Biome Replacer 1.5 to try and replace terralith skylands with ocean but I'm running into this NullPointerException. Terralith works on its own in vanilla & w/o the biome replacer jar in the /mods folder as well. Not sure if this is an error on my end but I'm not quite sure how to solve it.

My config file looks like this:
```
 terralith:skylands_autumn > minecraft:ocean
 terralith:skylands_spring > minecraft:ocean
 terralith:skylands_summer > minecraft:warm_ocean
 terralith:skylands_winter > minecraft:cold_ocean
```

The latest.log error looks like this:
```

[11:37:39] [Render thread/WARN]: Failed to validate datapack
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.Map.isEmpty()" because "net.werdei.biome_replacer.BiomeReplacer.replacementRules" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) [?:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.isEmpty()" because "net.werdei.biome_replacer.BiomeReplacer.replacementRules" is null
	at knot/net.werdei.biome_replacer.BiomeReplacer.noReplacements(BiomeReplacer.java:119) ~[biome_replacer-1.5.jar:?]
	at knot/net.minecraft.class_4766.findAndReplace(class_4766.java:537) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4766.handler$zzb000$biome_replacer$parameters(class_4766.java:530) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4766.method_49506(class_4766.java:50) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4766.method_49494(class_4766.java:58) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1966.method_49495(class_1966.java:32) ~[client-intermediary.jar:?]
	at knot/com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_1966.redirect$zzc000$fabric-biome-api-v1$getBiomes(class_1966.java:534) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1966.method_28443(class_1966.java:42) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2794.method_44215(class_2794.java:102) ~[client-intermediary.jar:?]
	at knot/com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_2794.method_59825(class_2794.java:106) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7193.method_60345(class_7193.java:71) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_525.method_59841(class_525.java:607) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 14 more
```

**Comment by LegendarySpy** [comment]
1.21.1 requires Java 21 or above. Have you tried it with Java 21?

**Comment by jenzelc** [comment]
Ah, I updated to 21.0.5 and I'm still getting the same error. I'm on Fabric 0.16.7-1.21.1 though, could that be an issue?

**Comment by WerDei** [comment]
This looks like another ordering issue, perhaps? Since rules are null? 
I can't reproduce this, but I have a code change I've made to prevent this from happening, at least in theory. I'll try to put it out today/tomorrow, and we'll see if it helps

**Comment by WerDei** [comment]
Just uploaded version 1.6, let me know if anything changed!

**Comment by jenzelc** [comment]
Works perfectly now! Thank you guys so much! <3
